name: Debugging with SSH
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1
     - uses: szenius/set-timezone@v1.0 # 设置执行环境的时区
       with:
          timezoneLinux: "Asia/Shanghai"
     - name: Try Build
       run: ./not-exist-file.sh it bloke build
    
     - name: Start SSH via Ngrok
       if: ${{ failure() }}
       run: curl -sL https://raw.githubusercontent.com/qiye1001/Test/main/debug-github-actions.sh | bash
       env:
        # After sign up on the https://ngrok.com/
        # You can find this token here: https://dashboard.ngrok.com/get-started/setup
        NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
 
        # This password you will use when authorizing via SSH 
        USER_PASS: ${{ secrets.USER_PASS }}
 
     - name: Don't kill instace
       if: ${{ failure() }}
       run: sleep 1h # Prevent to killing instance after failure
